ViewModels/SellerViewModel.cs
using HouseRentManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HouseRentManagement.ViewModels
{
    public  class SellerViewModel
    {
        public IEnumerable<Seller_Data> SellerData { get; set; }
        public IEnumerable<Property_Details> PropertyDetails { get; set; }
    }
}

Controllers/SellerController.cs
using HouseRentManagement.Controllers;
using HouseRentManagement.Models;
using HouseRentManagement.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HouseRentManagement.Controllers
{
    public class SellerController : Controller
    {
        // GET: Seller
        private HouseRentContext _context;
        public SellerController()
        {
            _context = new HouseRentContext();
        }
        //method for returning property details
        public Object PropertyDetails()
        {

            if (Session["sellerMail"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            string email = Session["sellerMail"].ToString();
            var GetSeller = _context.SellerDetail.ToList().Where(c => c.Email.Equals(email)).FirstOrDefault();
            Session["sellerID"] = GetSeller.Id;
            var model = new SellerViewModel
            {
                SellerData = _context.SellerDetail.ToList().Where(c => c.Email.Equals(email)),
                PropertyDetails = _context.PropertyDetails.ToList().Where(c => c.SellerID.Equals(Session["sellerID"])),
            };
            return model;
        }
        public ActionResult Index()
        {
            if (Session["sellerMail"] == null)
            {
                return RedirectToAction("Login", "Home");
            }

            return View("Seller_Index", PropertyDetails());
        }
        public ActionResult BookingDetails(int Id)
        {
            var SellerBookings = _context.BookingDetails.ToList().Where(c => c.SellerID == Id);
            var SellerProperties = new List<Property_Details>();
            foreach (var property in SellerBookings)
            {
                SellerProperties.Add(_context.PropertyDetails.Single(c => c.Id == property.PropertyId));
            }
            var SellerBookingDetails = new AllViewsModels()
            {
                GetSellers = _context.SellerDetail.Where(C => C.Id == Id),
                GetProperties = SellerProperties.Distinct(),
                GetBookings = SellerBookings,
                GetCustomers = _context.CustomerDetail.ToList()
            };
            return View("Seller_BookingDetails", SellerBookingDetails);
        }
        public ActionResult BookingHistory(int Id)
        {
            var SellerBookings = _context.BookingDetails.ToList().Where(c => c.SellerID == Id);
            var SellerProperties = new List<Property_Details>();
            foreach (var property in SellerBookings)
            {
                SellerProperties.Add(_context.PropertyDetails.Single(c => c.Id == property.PropertyId));
            }
            var SellerBookingDetails = new AllViewsModels()
            {
                GetSellers = _context.SellerDetail.Where(C => C.Id == Id),
                GetProperties = SellerProperties.Distinct(),
                GetBookings = SellerBookings,
                GetCustomers = _context.CustomerDetail.ToList()
            };
            return View("Seller_BookingHistory", SellerBookingDetails);
        }
        public ActionResult Edit(int? id)
        {
            var EditData = _context.SellerDetail.SingleOrDefault(c => c.Id == id);
            Session["imgpath"] = EditData.ProfilePic;
            return View("Seller_Edit", EditData);
        }
        public ActionResult EditData(Seller_Data EditData, HttpPostedFileBase imageEdit)
        {

            if (imageEdit == null)
            {
                EditData.ProfilePic = Session["imgpath"].ToString();
                _context.Entry(EditData).State = System.Data.Entity.EntityState.Modified;
                _context.SaveChanges();
            }
            else
            {
                string extension = Path.GetExtension(imageEdit.FileName);
                string filename = EditData.Name + DateTime.Now.ToString("-ddMMyy_hhmmss") + extension;

                string filepath = Path.Combine(Server.MapPath("~/Images/SellerImages/"), filename);
                imageEdit.SaveAs(filepath);
                EditData.ProfilePic = "~/Images/SellerImages/" + filename;
                _context.Entry(EditData).State = System.Data.Entity.EntityState.Modified;
                _context.SaveChanges();
                string oldImage = Request.MapPath(Session["imgpath"].ToString());
                if (System.IO.File.Exists(oldImage))
                {
                    System.IO.File.Delete(oldImage);

                }
            }
            var Editedmodel = new SellerViewModel
            {
                SellerData = _context.SellerDetail.ToList().Where(c => c.Email.Equals(Session["sellerMail"])),
                PropertyDetails = _context.PropertyDetails.ToList().Where(c => c.SellerID.Equals(Session["sellerID"])),
            };
            return View("Seller_Index", Editedmodel);

        }
        public ActionResult CreateProperty()
        {
            return View("Seller_AddProperty");
        }

        public string ImageName(int order)
        {
            string name = "";
            if (order == 1)
                name = "Home";
            if (order == 2)
                name = "Hall";
            if (order == 3)
                name = "BedRoom";
            if (order == 4)
                name = "Kitchen";
            return name;
        }
        public ActionResult AddProperty(Property_Details details, IEnumerable<HttpPostedFileBase> propertyImage)
        {

            details.SellerID = Convert.ToInt32(Session["sellerID"]);
            details.Current_Status = "Available";
            int order = 1;
            if (propertyImage != null)
            {
                foreach (var item in propertyImage)
                {
                    string extension = Path.GetExtension(item.FileName);
                    string filename = "S" + details.SellerID + "_" + ImageName(order) + DateTime.Now.ToString("-ddMM_HHmmss") + extension;
                    string filepath = Path.Combine(Server.MapPath("~/Images/PropertyImages/"), filename);
                    item.SaveAs(filepath);
                    if (order == 1)
                        details.Front_View_img = "~/Images/PropertyImages/" + filename;
                    if (order == 2)
                        details.Hall_img = "~/Images/PropertyImages/" + filename;
                    if (order == 3)
                        details.Bedroom_img = "~/Images/PropertyImages/" + filename;
                    else
                        details.Kitchen_img = "~/Images/PropertyImages/" + filename;

                    order++;

                }
            }
            else
            {
                return View("Seller_AddProperty");
            }

            _context.PropertyDetails.Add(details);
            _context.SaveChanges();
            return View("Seller_Index", PropertyDetails());
        }
       
        public ActionResult ViewPropertyDetails(int? id)
        {
            var PropertyDetails = _context.PropertyDetails.ToList().SingleOrDefault(c => c.Id.Equals(id));

            return View("Seller_ViewPropertyDetails", PropertyDetails);
        }
        public ActionResult EditProperty(int? id)
        {
            var PropertyDetails = _context.PropertyDetails.SingleOrDefault(c => c.Id == id);

            Session["Frontview"] = PropertyDetails.Front_View_img;
            Session["HallImg"] = PropertyDetails.Hall_img;
            Session["BedroomImg"] = PropertyDetails.Bedroom_img;
            Session["KitchenImg"] = PropertyDetails.Kitchen_img;

            return View("Seller_EditProperty", PropertyDetails);
        }
        public string SavedImage(HttpPostedFileBase item, Property_Details details, int order, string Image)
        {
            string oldImage = Request.MapPath(Image);
            if (System.IO.File.Exists(oldImage))
            {
                System.IO.File.Delete(oldImage);

            }
            string extension = Path.GetExtension(item.FileName);
            string filename = "S" + details.SellerID + "_" + ImageName(order) + DateTime.Now.ToString("-ddMM_HHmmss") + extension;
            string filepath = Path.Combine(Server.MapPath("~/Images/PropertyImages/"), filename);
            item.SaveAs(filepath);

            return filename;
        }

        public ActionResult EditedProperty(Property_Details details, IEnumerable<HttpPostedFileBase> propertyImage, int? id)
        {
            details.SellerID = Convert.ToInt32(Session["sellerID"]);
            details.Current_Status = "Available";
            int order = 1;

            foreach (var item in propertyImage)
            {
                if (order == 1)
                    details.Front_View_img = item is null ? Session["Frontview"].ToString() : "~/Images/PropertyImages/" + SavedImage(item, details, order, Session["Frontview"].ToString());
                else if (order == 2)
                    details.Hall_img = item is null ? Session["HallImg"].ToString() : "~/Images/PropertyImages/" + SavedImage(item, details, order, Session["HallImg"].ToString());
                else if (order == 3)
                    details.Bedroom_img = item is null ? Session["BedroomImg"].ToString() : "~/Images/PropertyImages/" + SavedImage(item, details, order, Session["BedroomImg"].ToString());
                else if(order==4)
                    details.Kitchen_img = item is null ? Session["KitchenImg"].ToString() : "~/Images/PropertyImages/" + SavedImage(item, details, order, Session["KitchenImg"].ToString());

                order++;
            }
            _context.Entry(details).State = System.Data.Entity.EntityState.Modified;
            _context.SaveChanges();
            var PropertyDetails = _context.PropertyDetails.SingleOrDefault(c => c.Id == id);

Views/Seller/Seller_BookingDetails.cshtml
@model HouseRentManagement.ViewModels.AllViewsModels

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Seller BookingDetails</title>
    <style>


        .booking-lists {
            margin-top: 100px;
        }

        .card {
            width: 90%;
            margin: 20px auto;
        }

        .table-sm th,
        .table-sm td {
            white-space: nowrap;
            width: 1%;
        }
    </style>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark p-3"
             style="background-color: rgba(26, 26, 31, 0.7)">
            <button class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarTogglerDemo01"
                    aria-controls="navbarTogglerDemo01"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                    <a class="navbar-brand ml-4" href="@Url.Action("Index")">HOUSERENT</a>
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item mr-2">
                            <a class="nav-link" href="@Url.Action("Index")">HOME</a>

                        </li>
                        <li class="nav-item mr-2 active">
                            <a class="nav-link" href="@Url.Action("BookingDetails", new { @id = Model.GetSellers.FirstOrDefault().Id })">BOOKING DETAILS</a>
                        </li>
                        <li class="nav-item mr-2">
                            <a class="nav-link" href="@Url.Action("BookingHistory", new { @id = Model.GetSellers.FirstOrDefault().Id })">REQUEST HISTORY</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav navbar-right">
                        <li class="nav-item mr-2">
                            <a role="button"
                               class="btn btn-primary"
                               href="@Url.Action("CreateProperty")">
                                Add Property
                            </a>
                        </li>
                        <li class="nav-item mr-2 ">
                            <a role="button"
                               class="btn btn-danger"
                               href="@Url.Action("Logout")">
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>
    </div>
    <div class="booking-lists">
        @if (Model.GetBookings != null)
        {
            foreach (var item in Model.GetBookings)
            {
                if (item.Booking_Status == "Requested")
                {
                    foreach (var getCustomer in Model.GetCustomers.Where(c => c.Id == item.CustomerId))
                    {

                        <div class="card" style="max-width: 100%; border-radius: 10px">
                            <div class="row no-gutters">
                                <div class="col-md-2 m-4">
                                    <img src="@Url.Content(getCustomer.ProfilePic)"
                                         style="border-radius: 50%"
                                         class="w-100"
                                         height="250" />
                                </div>
                                <div class="col-md-9 m-4">
                                    <div class="card-body">
                                        <div class="card-text">
                                            <hr />
                                            <table class="table-responsive table-fit table-sm">
                                                <thead class="thead-inverse">
                                                    <tr>
                                                        <th colspan="2">
                                                            <h4>@getCustomer.Name</h4>
                                                            <small class="text-muted">is intersted in your rental house</small>
                                                        </th>
                                                        <!-- <th></th> -->
                                                        <th>
                                                            <small class="text-muted">Mobile Number</small>
                                                            <h5>@getCustomer.MobileNumber</h5>
                                                        </th>
                                                        <th>
                                                            <small class="text-muted">Mail</small>
                                                            <h5>@getCustomer.Email</h5>
                                                        </th>
                                                    </tr>
                                                </thead>

                                                @foreach (var getProperty in Model.GetProperties.Where(c => c.Id == item.PropertyId))
                                                {

                                                    <tbody>
                                                        <tr>
                                                            <td>
                                                                <h4>@getProperty.Property_Name</h4>
                                                                <small class="text-muted m-0">@getProperty.Property_Locality,@getProperty.Property_City </small>
                                                            </td>
                                                            <td>
                                                                <small class="text-muted">BHK</small><br />
                                                                @getProperty.BHK
                                                            </td>
                                                            <td>
                                                                <small class="text-muted">Monthly Rent</small><br />
                                                                @getProperty.Monthly_Rent
                                                            </td>
                                                            <td>
                                                                <small class="text-muted">Dated on</small><br />
                                                                @item.Booked_Date

                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                }
                                            </table>
                                            <hr />
                                        </div>
                                    </div>
                                    <div class="col-10 mb-5">
                                        <a role="button"
                                           class="btn btn-danger mr-5 float-right col-5"
                                           href="@Url.Action("DeclineRequest", new { @id = item.Id })">
                                            Decline
                                        </a>
                                        <a role="button"
                                           class="btn btn-success mr-4 float-right col-5"
                                           href="@Url.Action("AcceptRequest", new { @id = item.Id })">
                                            Accept
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    }
                }
            }
        }
        else
        {
            <label class="text-black-50 text-center m-5">You didn't have any Request for your Houses</label>
        }
    </div>
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>

</body>
</html>

Views/Seller/Seller_Edit.cshtml
@model HouseRentManagement.Models.Seller_Data

@{
    ViewBag.Title = "Seller_Edit";
}

    <!-- Navbar -->
<nav class="navbar navbar-expand-lg fixed-top navbar-dark p-3"
     style="background-color: rgba(26, 26, 31, 0.7)">
    <button class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand ml-4" href="@Url.Action("Index")">Back to Home</a>
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            </ul>
            <ul class="navbar-nav navbar-right">
                <li class="nav-item mr-2 ">
                    <a role="button"
                       class="btn btn-danger"
                       href="@Url.Action("Logout")">
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
   

    <h2>Edit Data</h2>

    @using (Html.BeginForm("EditData", "Seller", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MobileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    <label class="text-info">*You can enter the old password or Create the NewPassword to confirm the Changes</label>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ProfilePic, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <img src="@Url.Content(Model.ProfilePic)" width="50" height="50" /><br />
                    <input type="file" id="imageEdit" name="imageEdit" />
                    @Html.ValidationMessageFor(model => model.ProfilePic, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save Changes" class="btn btn-success btn-block" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
 

Views/Seller/Seller_Index.cshtml
@model HouseRentManagement.ViewModels.SellerViewModel


@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SellerIndex</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link href="~/StyleSheet/SellerCSS/Seller_Index.css" rel="stylesheet" />
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark p-3"
         style="background-color: rgba(26, 26, 31, 0.7)">
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor02">
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <a class="navbar-brand ml-4" href="@Url.Action("Index")">HOUSERENT</a>
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item mr-2 active">
                        <a class="nav-link" href="@Url.Action("Index")">HOME</a>

                    </li>
                    <li class="nav-item mr-2">
                        <a class="nav-link" href="@Url.Action("BookingDetails", new { @id = Model.SellerData.FirstOrDefault().Id })">BOOKING DETAILS</a>
                    </li>
                    <li class="nav-item mr-2">
                        <a class="nav-link" href="@Url.Action("BookingHistory", new { @id = Model.SellerData.FirstOrDefault().Id })">REQUEST HISTORY</a>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-right">
                    <li class="nav-item mr-2">
                        <a role="button"
                           class="btn btn-primary"
                           href="@Url.Action("CreateProperty")">
                            Add Property
                        </a>
                    </li>
                    <li class="nav-item mr-2 ">
                        <a role="button"
                           class="btn btn-danger"
                           href="@Url.Action("Logout")">
                            Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>

    </nav>
    <!-- Main Card -->
    <div class="card float-left" id="center">
        <div class="card-body">
            <h4 class="card-title">
                PROPERTIES
                <i class="fa fa-home" aria-hidden="true"></i>
            </h4>
            <div class="form-row">
                @foreach (var item in Model.PropertyDetails)
                {
                    <div class="col-md-4">
                        <div class="card">
                            <img class="card-img-top"
                                 src="@Url.Content(@item.Front_View_img)"
                                 height="200"
                                 alt="Card-image" />
                            <div class="card-body">
                                <div class="float-left"> <h5 class="card-title font-weight-bolder text-uppercase"><u>@item.Property_Name</u></h5></div>
                                <p class="float-right">&#8377;@item.Monthly_Rent</p>
                                <br />
                                <p class="card-text">
                                    <h6 class="float-left">@item.Current_Status</h6>
                                    <a href="@Url.Action("ViewPropertyDetails","Seller",new{@id=item.Id})" class="float-right text-muted">View Details</a>
                                </p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- Side Card -->
    <div class="card float-right" id="side">
        <div class="card-body">
            <h4 class="card-title">
                <i class="fa fa-user" aria-hidden="true"></i>
                PROFILE
                <a href="@Url.Action("Edit", "Seller",new { @id=Model.SellerData.FirstOrDefault().Id})">
                    <i class="fa fa-pencil-square-o"
                       aria-hidden="true"
                       style="float: right; color:black"></i>
                </a>
            </h4>
            <div class="card-text">
                @foreach (var item in Model.SellerData)
                {

                    <img class="card-img-top rounded-circle"
                         src="@Url.Content(@item.ProfilePic)"
                         alt="profile"
                         height="250"
                         style="padding: 5px 25px" />
                }


                <table class="table-responsive-md">
                    <tr>
                        <th> @Html.DisplayFor(model => model.SellerData.FirstOrDefault().Name)</th>
                    </tr>
                    <tbody>
                        <tr>
                            <td> @Html.DisplayFor(model => model.SellerData.FirstOrDefault().Email)</td>
                        </tr>
                        <tr>
                            <td> @Html.DisplayFor(model => model.SellerData.FirstOrDefault().MobileNumber)</td>
                        </tr>
                        <tr>
                            <td style="text-transform:uppercase;"> @Html.DisplayFor(model => model.SellerData.FirstOrDefault().State)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</body>
</html>